"""TASAS city letter codes for the Clean Road builds (v0.29.1).

The TSMIS City layer carries city NAMES (and occasionally the code itself);
TSN's clean-road extracts carry the TASAS letter codes. This table was
DERIVED EMPIRICALLY on 2026-07-22 by co-locating the layer's as-of SHS city
spans with the statewide CA HIGHWAYS extract's city-coded rows (county + PM;
21,906 rows voted; 99.92% agreement; the one sub-90% vote — ALHAMBRA, whose
boundary rows bleed into SPAS/PAS/LA — resolved to its 67% majority ALH).
Derivation script: the local corpus _inbox/Cleanroad/_analysis/
derive_city_codes.py. An unmapped name passes through verbatim so it
SURFACES in a comparison instead of vanishing.
"""

CITY_CODES = {
    'ADELANTO': 'ADEL',
    'AGOURA HILLS': 'AGRH',
    'ALAMEDA': 'ALA',
    'ALBANY': 'ALB',
    'ALHAMBRA': 'ALH',
    'ALTURAS': 'ALT',
    'AMERICAN CANYON': 'AMCN',
    'ANAHEIM': 'ANA',
    'ANDERSON': 'AND',
    'ANGELS': 'ANG',
    'ANTIOCH': 'ANT',
    'APPLE VALLEY': 'APLV',
    'ARCATA': 'ARC',
    'ARROYO GRANDE': 'ARGD',
    'ARTESIA': 'ART',
    'ARVIN': 'ARV',
    'ATASCADERO': 'ATAS',
    'ATHERTON': 'ATN',
    'ATWATER': 'ATW',
    'AUBURN': 'AUB',
    'AVENAL': 'AVNL',
    'BAKERSFIELD': 'BKD',
    'BALDWIN PARK': 'BWP',
    'BANNING': 'BAN',
    'BARSTOW': 'BSW',
    'BEAUMONT': 'BAU',
    'BELL': 'BELL',
    'BELLFLOWER': 'BFL',
    'BELMONT': 'BMT',
    'BENICIA': 'BEN',
    'BERKELEY': 'BER',
    'BISHOP': 'BIS',
    'BLYTHE': 'BLY',
    'BRAWLEY': 'BRW',
    'BREA': 'BRE',
    'BRISBANE': 'BSBN',
    'BUENA PARK': 'BPK',
    'BURBANK': 'BRB',
    'BURLINGAME': 'BURL',
    'CALABASAS': 'CAL',
    'CALEXICO': 'CLX',
    'CALIMESA': 'CMSA',
    'CALIPATRIA': 'CLP',
    'CALISTOGA': 'CSTG',
    'CAMARILLO': 'CMRL',
    'CAMPBELL': 'CMB',
    'CAPITOLA': 'CPTL',
    'CARLSBAD': 'CBD',
    'CARPINTERIA': 'CARP',
    'CARSON': 'CRSN',
    'CATHEDRAL CITY': 'CTHC',
    'CERES': 'CER',
    'CERRITOS': 'CRTS',
    'CHICO': 'CHC',
    'CHINO': 'CHN',
    'CHINO HILLS': 'CHNH',
    'CHOWCHILLA': 'CHW',
    'CHULA VISTA': 'CHV',
    'CLAREMONT': 'CLA',
    'CLEARLAKE': 'CLLK',
    'CLOVERDALE': 'CLVD',
    'COACHELLA': 'COA',
    'COALINGA': 'CLNG',
    'COLFAX': 'CFX',
    'COLMA': 'CLM',
    'COLTON': 'COL',
    'COLUSA': 'CLU',
    'COMMERCE': 'CMRC',
    'COMPTON': 'COM',
    'CONCORD': 'CND',
    'CORCORAN': 'CRCN',
    'CORONA': 'COR',
    'CORONADO': 'CORD',
    'CORTE MADERA': 'CMAD',
    'COSTA MESA': 'CMS',
    'COTATI': 'COTI',
    'CRESCENT CITY': 'CRC',
    'CULVER CITY': 'CLC',
    'CUPERTINO': 'CPO',
    'DALY CITY': 'DLC',
    'DANA POINT': 'DAPT',
    'DANVILLE': 'DNVL',
    'DAVIS': 'DVS',
    'DEL REY OAKS': 'DRO',
    'DELANO': 'DLN',
    'DIAMOND BAR': 'DMBR',
    'DIXON': 'DXN',
    'DORRIS': 'DRS',
    'DOS PALOS': 'DPLS',
    'DOWNEY': 'DNY',
    'DUBLIN': 'DBLN',
    'DUNSMUIR': 'DMR',
    'EAST OAKDALE': 'EPAO',
    'EL CAJON': 'ECJ',
    'EL CENTRO': 'ECN',
    'EL CERRITO': 'ECR',
    'EL MONTE': 'EMTE',
    'EL PASO DE ROBLES': 'PSRS',
    'EL SEGUNDA': 'ESEG',
    'EMERYVILLE': 'EMV',
    'ENCINITAS': 'ENTS',
    'ESCALON': 'ESL',
    'ESCONDIDO': 'ESD',
    'ETNA': 'ETN',
    'EUREKA': 'EUR',
    'EXETER': 'EXR',
    'FAIRFIELD': 'FRFD',
    'FERNADALE': 'FER',
    'FILLMORE': 'FIL',
    'FIREBAUGH': 'FIR',
    'FONTANA': 'FNA',
    'FORT BRAGG': 'FBG',
    'FORT JONES': 'FJN',
    'FORTUNA': 'FTA',
    'FOSTER CITY': 'FSTC',
    'FOUNTAIN VALLEY': 'FNV',
    'FOWLER': 'FOW',
    'FREMONT': 'FMT',
    'FRESNO': 'FRE',
    'FULLERTON': 'FUL',
    'GALT': 'GAL',
    'GARDEN GROVE': 'GGR',
    'GILROY': 'GIL',
    'GLANDALE': 'GNDL',
    'GLENDORA': 'GDR',
    'GONZALES': 'GNZ',
    'GRAND TERRACE': 'GRTR',
    'GRASS VALLEY': 'GVY',
    'GREENFIELD': 'GNFD',
    'GRIDLEY': 'GRD',
    'GROVER CITY': 'GRC',
    'GUADALUPE': 'GDLP',
    'GUSTINE': 'GUS',
    'HALF MOON BAY': 'HMBY',
    'HANFORD': 'HAN',
    'HAWTHORNE': 'HAW',
    'HAYWARD': 'HAY',
    'HEALDSBURG': 'HLBG',
    'HEMET': 'HEM',
    'HERCULES': 'HER',
    'HERMOSA BEACH': 'HMB',
    'HESPERIA': 'HES',
    'HIGHLAND': 'HIGH',
    'HILLSBOROUGH': 'HIL',
    'HOLLISTER': 'HST',
    'HOLTVILLE': 'HOLT',
    'HUNTINGTON BEACH': 'HNTB',
    'HURON': 'HRN',
    'INDIO': 'IND',
    'INDUSTRY': 'IDY',
    'INGLEWOOD': 'ING',
    'IONE': 'ION',
    'IRVINE': 'IRVN',
    'IRWINDALE': 'IRW',
    'ISLETON': 'IST',
    'JACKSON': 'JKN',
    'KERMAN': 'KMN',
    'KING CITY': 'KNC',
    'KINGSBURG': 'KNGB',
    'LA CANADA-FLINTRIDGE': 'LCF',
    'LA HABRA': 'LHB',
    'LA MESA': 'LMSA',
    'LA MIRADA': 'LMRD',
    'LA VERNE': 'LVN',
    'LAFAYETTE': 'LFYT',
    'LAGUNA BEACH': 'LGNB',
    'LAGUNA HILLS': 'LGNH',
    'LAKE ELSINORE': 'ESN',
    'LAKE FOREST': 'LKFR',
    'LAKEPORT': 'LKPT',
    'LAKEWOOD': 'LKW',
    'LANCASTER': 'LAN',
    'LARKSPUR': 'LKSP',
    'LATHROP': 'LTRP',
    'LAWNDALE': 'LNDL',
    'LEMON GROVE': 'LMGR',
    'LEMOORE': 'LEM',
    'LGNG': 'LGNG',
    'LINDSAY': 'LNSY',
    'LIVE OAK': 'LIO',
    'LIVERMORE': 'LVMR',
    'LIVINGSTON': 'LVTN',
    'LODI': 'LOD',
    'LOMA LINDA': 'LMLN',
    'LOMITA': 'LMTA',
    'LOMPOC': 'LOM',
    'LONG BEACH': 'LBCH',
    'LOOMIS': 'LMS',
    'LOS ALAMITOS': 'LALM',
    'LOS ALTOS': 'LATS',
    'LOS ALTOS HILLS': 'LAH',
    'LOS ANGELES': 'LA',
    'LOS BANOS': 'LBNS',
    'LOS GATOS': 'LGTS',
    'LOYALTON': 'LOY',
    'LYN': 'LYN',
    'MADERA': 'MAD',
    'MAL': 'MAL',
    'MAMMOTH LAKES': 'MMLK',
    'MANHATTAN BEACH': 'MANB',
    'MANTECA': 'MTCA',
    'MARICOPA': 'MCP',
    'MARINA': 'MRNA',
    'MARTINEZ': 'MTZ',
    'MARYSVILLE': 'MVL',
    'MCFARLAND': 'MCF',
    'MENDOTA': 'MDA',
    'MENLO PARK': 'MLP',
    'MERCED': 'MER',
    'MILLBRAE': 'MLBR',
    'MILPITAS': 'MPS',
    'MISSION VIEJO': 'MSNV',
    'MOD': 'MOD',
    'MON': 'MON',
    'MONTAGUE': 'MNTG',
    'MONTCLAIR': 'MCL',
    'MONTE SERENO': 'MSO',
    'MONTEBELLO': 'MTBL',
    'MONTEREY PARK': 'MONP',
    'MOORPARK': 'MRPK',
    'MORENO VALLEY': 'MORV',
    'MORGAN HILL': 'MGH',
    'MORRO BAY': 'MOBY',
    'MOUNT SHASTA': 'MSHA',
    'MOUNTAIN VIEW': 'MVW',
    'MURRIETA': 'MRTA',
    'NAPA': 'NAP',
    'NATIONAL CITY': 'NATC',
    'NEEDLES': 'NED',
    'NEVADA CITY': 'NEVC',
    'NEWARK': 'NWK',
    'NEWMAN': 'NEWM',
    'NEWPORT BEACH': 'NPTB',
    'NORCO': 'NRCO',
    'NORWALK': 'NRW',
    'NOVATO': 'NVTO',
    'OAKDALE': 'OKDL',
    'OAKLAND': 'OAK',
    'OCEANSIDE': 'OCN',
    'OJAI': 'OJI',
    'ONTARIO': 'ONT',
    'ORANGE': 'ORA',
    'ORANGE COVE': 'ORCV',
    'ORINDA': 'ORIN',
    'ORLAND': 'ORL',
    'OROVILLE': 'OVL',
    'OXNARD': 'OXN',
    'PACIFIC GROVE': 'PGR',
    'PACIFICA': 'PFA',
    'PALM SPRINGS': 'PSP',
    'PALMDALE': 'PMDL',
    'PALO ALTO': 'PA',
    'PARADISE': 'PRDS',
    'PARAMOUNT': 'PRM',
    'PASADENA': 'PAS',
    'PATTERSON': 'PAT',
    'PERRIS': 'PER',
    'PETALUMA': 'PET',
    'PICO RIVERA': 'PRV',
    'PINOLE': 'PIN',
    'PISMO BEACH': 'PBCH',
    'PITTSBURG': 'PIT',
    'PLACENTIA': 'PLCN',
    'PLACERVILLE': 'PLCR',
    'PLEASANT HILL': 'PLHL',
    'PLEASANTON': 'PLE',
    'PLYMOUTH': 'PLY',
    'POINT ARENA': 'PTA',
    'POMONA': 'POM',
    'PORTERVILLE': 'PTRV',
    'PORTOLA': 'PRTL',
    'POWAY': 'PWY',
    'RANCHO CUCAMONGA': 'RCUC',
    'RANCHO PALOS VERDES': 'ROPV',
    'RANCHO SANTA MARGARITA': 'RSM',
    'RED BLUFF': 'RBL',
    'REDDING': 'RDG',
    'REDLANDS': 'RDL',
    'REDONDO BEACH': 'RDOB',
    'REDWOOD CITY': 'RDWC',
    'RIALTO': 'RIA',
    'RICHMOND': 'RCH',
    'RIDGECREST': 'RGCR',
    'RIO DELL': 'RDEL',
    'RIO VISTA': 'RVS',
    'RIPON': 'RIP',
    'RIVERSIDE': 'RIV',
    'ROCKLIN': 'ROC',
    'ROHNERT PARK': 'RNPK',
    'ROSEMEAD': 'RSMD',
    'ROSEVILLE': 'RSV',
    'SACRAMENTO': 'SAC',
    'SAINT HELENA': 'SHLA',
    'SALINAS': 'SAL',
    'SAN BERNARDINO': 'SBD',
    'SAN BRUNO': 'SBR',
    'SAN BUENAVENTURA': 'VEN',
    'SAN CARLOS': 'SCAR',
    'SAN CLEMENTE': 'SCLE',
    'SAN DIEGO': 'SD',
    'SAN DIMAS': 'SDMS',
    'SAN FRANCISCO': 'SF',
    'SAN JOSE': 'SJS',
    'SAN JUAN BAUTISTA': 'SJB',
    'SAN JUAN CAPISTRANO': 'SJCP',
    'SAN LEANDRO': 'SLN',
    'SAN LUIS OBISPO': 'SLO',
    'SAN MARCOS': 'SMCS',
    'SAN MATEO': 'SM',
    'SAN PABLO': 'SPB',
    'SAN RAFAEL': 'SRF',
    'SAN RAMON': 'SRMN',
    'SAND CITY': 'SNDC',
    'SANTA ANA': 'SA',
    'SANTA BARBARA': 'SB',
    'SANTA CLARA': 'SCL',
    'SANTA CLARITA': 'SCTA',
    'SANTA CRUZ': 'SCR',
    'SANTA FE SPRINGS': 'SFSP',
    'SANTA MARIA': 'SMRA',
    'SANTA MONICA': 'SMCA',
    'SANTA PAULA': 'SPA',
    'SANTA ROSA': 'SRO',
    'SANTEE': 'SNT',
    'SARATOGA': 'SAR',
    'SAUSALITO': 'SAUS',
    'SCOTTS VALLEY': 'SCTV',
    'SEAL BEACH': 'SLB',
    'SEASIDE': 'SEA',
    'SEBASTOPOL': 'SEB',
    'SELMA': 'SEL',
    'SHASTA LAKE': 'SHLK',
    'SIGNAL HILL': 'SIGH',
    'SIMI VALLEY': 'SIMV',
    'SOLANA BEACH': 'SOLB',
    'SOLEDAD': 'SOL',
    'SOLVANG': 'SLVG',
    'SONOMA': 'SON',
    'SONORA': 'SRA',
    'SOUTH EL MONTE': 'SEMT',
    'SOUTH GATE': 'SGT',
    'SOUTH LAKE TAHOE': 'SLTO',
    'SOUTH PASADENA': 'SPAS',
    'SOUTH SAN FRANCISCO': 'SSF',
    'STANTON': 'STT',
    'STOCKTON': 'STKN',
    'SUISUN CITY': 'SUIS',
    'SUNNYVALE': 'SUNV',
    'SUSANVILLE': 'SUSV',
    'TAFT': 'TAF',
    'TEHACHAPI': 'THPI',
    'TEMECULA': 'TMCA',
    'TEMPLE CITY': 'TMPC',
    'THOUSAND OAKS': 'THOK',
    'TIBURON': 'TBRN',
    'TORRANCE': 'TOR',
    'TRACY': 'TRA',
    'TRINIDAD': 'TRND',
    'TRUCKEE': 'TRK',
    'TULARE': 'TUL',
    'TURLOCK': 'TUR',
    'TUSTIN': 'TUS',
    'TWENTYNINE PALMS': 'TNP',
    'UKIAH': 'UKI',
    'UNION CITY': 'UNC',
    'UPLAND': 'UPL',
    'VACAVILLE': 'VAC',
    'VALLEJO': 'VAL',
    'VERNON': 'VER',
    'VICTORVILLE': 'VCTV',
    'VISALIA': 'VIS',
    'VISTA': 'VSTA',
    'WALNUT CREEK': 'WLC',
    'WASCO': 'WAS',
    'WATERFORD': 'WTRF',
    'WATSONVILLE': 'WAT',
    'WEED': 'WEED',
    'WEST SACRAMENTO': 'WSAC',
    'WESTLAKE VILLAGE': 'WLKV',
    'WESTMINSTER': 'WTM',
    'WESTMORLAND': 'WMD',
    'WHEATLAND': 'WHT',
    'WHITTIER': 'WIT',
    'WILLIAMS': 'WMS',
    'WILLITS': 'WLTS',
    'WILLOWS': 'WLOS',
    'WINTERS': 'WIN',
    'WOODLAKE': 'WLK',
    'WOODLAND': 'WD',
    'WOODSIDE': 'WDS',
    'YCPA': 'YCPA',
    'YOUNTVILLE': 'YNTV',
    'YREKA CITY': 'YRE',
    'YUBA CITY': 'YC',
    'YUCCA VALLEY': 'YUCV',
}
_CODE_SET = frozenset(CITY_CODES.values())


def norm_city(v):
    """A City-layer value to its TASAS city code: names translate via the
    derived table, values that already ARE a known code pass through, and an
    unmapped value returns stripped/upper-cased so it stays visible."""
    s = ("" if v is None else str(v)).strip().upper()
    if not s:
        return ""
    if s in CITY_CODES:
        return CITY_CODES[s]
    return s
